language: python

python:
- '3.8'

services:
- postgresql

install:
- pip install -r requirements.txt
- pip install coveralls

script:
- coverage run --source=. --omit=custom_storages.py,checkout/webhook*,config/*,manage.py,users/adapter.py manage.py test --keepdb

after_success:
  - coveralls

deploy:
  provider: heroku
  api_key:
    secure: QalLHBxSewu0wnkNpx6BaKQ8AbZ6wI50pNkTpFwoy0cmU67GOwfIWHUdeX5sqFem7Vp2vIJkoF7ETQLb4Tjaz0gV85fGM8qNBADVUYcfdUzxhGEzf50me6yBwlWvwU2ETtaQ3iWqHC0q5zF6jsIOJJiDa/k87lSREIWUInlps+U982JdgKbReG9gOJT+PdbJ8G3eaZWBVpNrj9lbjyVVQ1ZMCuSypIstA+vsaABJLFt+JnZVna/2zacclaNlIUfUPhhnxlE3p8BlZENDewa1OyinqnriJ1nOz/6jyqCiz903n2WGQJO2siKvMEV6Voa1BYEOG1sbMDNwOgMQoTjs5tf4GDSP6MXMtFkXEYS59J1aazZ7TPdkovN5ZEJd0MgF+OfT24MbSftXzz4RMHZJM67XRwEgdEEsHnvt9bt3tKO5nNt5fj5AXXb2SGXf5NU9KzL8vbsDkAsVUBDEZgzF1hOd8k7MJPKS/pLVoTb7HXGaPAnbKTjbTAwNVYh1D2wnKLVcZSlivqDID+tRzoZfGgOt1WsBDNnHnT7BueMS3Ux6YtveJgrqFWaqOKUn3Di69BNEl3sGaOeiPWA7tp4QLs0oX5k8mbfAE96mlrG2BL3UgIBYH3LJrfICLzMWIAoMSE2XRT8kvtrsvh2g648lZ80jzTXILaLfaBNLvQTGtp0=
