language: python
python:
- '3.8'
services:
- postgresql
install:
- pip install -r requirements.txt
script:
- python manage.py test --keepdb
deploy:
  provider: heroku
  api_key:
    secure: oB8F+uKrCxrUTnUgbq6DYaaCS6R9TyiCes3NjYeUYpiPhoq+ocMSeO+k2oEJ4gVWS8RZ6J2qA+JBlcmTiFClMOsbWi63Zyv8NjOGbW8ij/RuaT6N1Mf0/jAlpDzeeLsxnmZpctl9eG6OME4C7pSh3UCQrYiKUZV+8xhgFrEuloW9+wsHOyNbWgf6kPTH4DFh4oUvBRK334VGlDwu5ZNd+MMGHxYbs5/TGmiF4yibUtbI2dmE5aUFw6eIJItbITdD7lWlmjV4ZM24db4Pw56x9YWkU4Y8+uWOpsdEhf2MTIrBR1PRoBi/LJdQBJyJN7kBkkfbjiySTuB1RYDjq5GFsLPrD89LIfflsUcY9VZdEgY7vNXcR2p17AEtjeOkF4wnslfLfRXR7JgOlNJhUSX4GBfy043pGJihT5D/N+cjHJcJN98bpTi8y2fO7vKqJnL1pvelBULnBs1EvZuhjq/FBseFyU628723+eNdx60DYjzO7JlO18U07bNlHDoB0TBYuhJMWE9AUWs6xuZGam8y2cCmBPs4/B5devnvpRpRqrfZAAm+foOmvFux2VvMxcag60RXrLcVi9FcToVvCYNE3PTZTRPSNOFLu3M2hhWivTKZsmU5b3N1E949oC96pX6Ixr0ZetQ3/mMYsxOSKFjT7dhAqSIvWVDUDG7unB2V0Pg=